### ISSUE TITLE
Question to download images blocks non-interactive emacs session

### ISSUE THREAD

**Issue by steckerhalter** [iqbalansari/emacs-emojify#33]
Maybe a custom like `emojify-download-images-p` with possible values 'ask (default) t and nil would do?

**Comment by iqbalansari** [comment]
Hi thanks for the bug report!

Yes that would work, plus I think I should skip the question (and downloading) altogether if Emacs is started in non-interactive mode and and `emojify-download-images-p` is `ask`.

**Comment by steckerhalter** [comment]
Sounds good :+1: Thanks

**Comment by iqbalansari** [comment]
I have pushed a fix on the master branch, should be available once MELPA builds. The variable is called `emojify-download-emojis-p` though I think you might not need it since in noninteractive mode the user will not be prompted for downloads.

**Comment by steckerhalter** [comment]
Thanks. I'm still having a bit of trouble with my build. The only way I could get it to run through was by setting `emojify-download-emojis-p` to nil. This happened with `t`: https://travis-ci.org/steckerhalter/steckemacs.el/builds/334401543 and the default `'ask` kept stalling: https://travis-ci.org/steckerhalter/steckemacs.el/builds/334394964

I'm not quite sure why though. I'll try again later.

**Comment by steckerhalter** [comment]
I just keep it on `nil` I guess. At least it finishes like that. Thanks for implementing...
